name = "Crankshaft Plugin Template"
version = "TODO"
link = "TODO"
source = "TODO"
min-crankshaft-version = "0.1.5"

[author]
name = "TODO"
link = "TODO"

[entrypoints]

	[entrypoints.desktop]
	library = true
	menu = false

	[entrypoints.deck]
	library = false
	menu = false
	quick-access = false
