name = "Flathub"
version = "1.0.0"
link = "https://github.com/ShadowBlip/crankshaft-flathub"
source = "https://github.com/ShadowBlip/crankshaft-flathub"
min-crankshaft-version = "0.2.1"

[author]
name = "William Edwards"
link = "https://github.com/ShadowApex"

[entrypoints]

	[entrypoints.desktop]
	library = true
	menu = false

	[entrypoints.deck]
	library = true
	menu = false
	quick-access = false

[store]
description = """
Crankshaft Flathub lets you easily browse, search, manage, and install Flatpaks
from Flathub from the comfort of the Steam UI.

This plugin uses the "steam-shortcut-manager" command-line tool to automatically
add your installed Flatpaks as Steam Library shortcuts, and tries to automatically
download the grid artwork for your Flatpak applications from SteamGridDB so they 
look nice in your Steam library.

NOTE: Crankshaft Flathub currently only works with a touchscreen/mouse and
keyboard. Gamepad and on-screen keyboard support is planned for a future release.
"""

