name = "Flathub"
version = "1.0.0"
link = "https://github.com/ShadowApex/crankshaft-flathub"
source = "https://github.com/ShadowApex/crankshaft-flathub"
min-crankshaft-version = "0.1.5"

[author]
name = "William Edwards"
link = "https://github.com/ShadowApex"

[entrypoints]

	[entrypoints.desktop]
	library = true
	menu = false

	[entrypoints.deck]
	library = true
	menu = false
	quick-access = false
