name: Test
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17'
      - name: Install dependencies
        run: make node_modules
      - name: Test
        run: make build

